// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://poxiebqqcbzkyhemkvxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBveGllYnFxY2J6a3loZW1rdnhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzMzNTUsImV4cCI6MjA2MjMwOTM1NX0.T7l_rxRBTE76e67hPr9ACX4BjuQORejDh3SQHGixQ6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);